import Head from 'next/head'
import React from 'react'
import Link from 'next/link'
// TODO get imports working.. 

import { Headline, Button, Icon, Label, Image, ImageOverlay } from '@smartive-education/pizza-hawaii'
import Atoms from './atoms/atoms'
import SimpleNav from './simpleNav'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
            <h2>Pizza Hawaii testpage </h2>
            <div>
            <SimpleNav />
            <Headline level={2} >Hi there <Icon name='heart_filled' size='L' /></Headline>
            <br />

            export default Home
            <Label as='p' size='M'>Welcome to testing Area</Label>
            
            <Button size='M' as='button' color='violet' icon='heart' >Button text</Button>
            <br />
            <Image src='//picsum.photos/id/28/1600/1587/' preset='post' alt='this is the alt text'/>
            <br />
            <ImageOverlay icon='share' overlayStyles='rounded-2xl' src='//picsum.photos/id/88/1610/1477/' />
            </div>
        </div>
      </main>
    </>
  )
}
